version: '2'
services:
  broker:
    image: penhalver/apache-apollo
    ports:
      - 61613:61613
  db:
    image: postgres
    environment:
      POSTGRES_DB: reports
      POSTGRES_PASSWORD: reports
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/connect
    ports:
      - 80:3000
      - 3000:3000
      - 1080:1080
    links:
      - db
      - broker
